### ISSUE TITLE
[BUG] Land mine positioning is slightly off

### ISSUE THREAD

**Issue by KenCoder** [teoxoy/factorio-blueprint-editor#236] opened 2022-02-24 14:23 UTC
**Describe the bug**
Importing then exporting a blueprint with a landmine produces a difference in the blueprint

**To Reproduce**

1. Create a blueprint in factory with a land mine and a conveyor belt (as above)
2. Export the blueprint from Factorio and import into FBE
3. Ctrl+C to export from FBE, then import into Factorio
4. Try to place the imported blueprint on top of the existing mine. 
5. You get the error "Land mine is in the way", and you can see that the pasted land mine is a little to the right.

**Expected behavior**
Re-imported blueprint should match original

**Screenshots**
The blueprint:
![image](https://user-images.githubusercontent.com/403709/155541116-fd107c57-a483-4ce2-a29f-0e2a6cafde92.png)

Error from step 5
![image](https://user-images.githubusercontent.com/403709/155541624-039d4238-1618-4904-93a5-7f39dddfcb99.png)

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Chrome

<details><summary><strong>Blueprint String from FBE</strong></summary>
0eJyFkN0KwjAMRt8l151oncz10tcQkc4FKXRpaTtxjL677QYy//CuKTknXzJCo3u0TlEAMYK6GPIgjiN4dSWp818YLIIAFbADBiS7XAUnyVvjQtGgDhAZKGrxDmIT2V9YS2qLThEuOB5PDJCCCgrnBFMxnKnvGnRJ/AVnYI1PhKE8K1mK9WrHYJgfMUd5s/BfG3yoXk0p3LSDWNyLwQ2dnwi+35RVzauS1/W2TlG1TNbUfXh2x/gAtWF28A==
</details>

**Comment by teoxoy** [comment] 2022-02-26 23:50
I think this is caused by the way landmines are imported. They will get aligned to the grid on import.

I thought importing them this way is more useful when editing. It's also easier to support due to the current collision detection data structure being a grid.

Having said that, let me know if you would still consider this a bug.

**Comment by KenCoder** [comment] 2022-02-27 05:19
In general, it's nice if blueprints can be pasted back into Factorio without misaligning. Having said that, if the only problem is land mines then I wouldn't spend any time on it as no-one is going to be using them in a blueprint. I found this in my rotation testing and wanted to record it.

**Comment by teoxoy** [comment] 2022-02-27 08:16
Let's close this for now then.

**Closed by teoxoy** 2022-02-27 08:16 UTC
Labels: bug
